// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "PracticalCombine",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "PracticalCombine",
            targets: ["AppModule"],
            bundleIdentifier: "jp.co.sashimon.practical-combine.PracticalCombine",
            teamIdentifier: "2JC6RUY73H",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .bird),
            accentColor: .presetColor(.green),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/icanzilb/TimelaneCombine", "2.0.0"..<"3.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "TimelaneCombine", package: "timelanecombine")
            ],
            path: "."
        )
    ]
)