# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SizeThatFitsSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'SnapKit'

  # Pods for SizeThatFitsSample

  target 'SizeThatFitsSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SizeThatFitsSampleUITests' do
    # Pods for testing
  end

end
